version: '3.8'

services:
  postgres:
    build: ./app/docker/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Local directory
      - ./app/docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    build: ./app/docker/redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data  # Also use local directory for Redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes

  backend:
    build: ./app/docker/fastapi
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - ENVIRONMENT=${ENVIRONMENT}
      - SECRET_KEY=${SECRET_KEY}
      - AZURE_CV_ENDPOINT=${AZURE_CV_ENDPOINT}
      - AZURE_CV_KEY=${AZURE_CV_KEY}
    volumes:
      - ./app/backend:/app
      - ./app/docker/fastapi/requirements.txt:/tmp/requirements.txt
      - ./storage:/app/storage
      - ./models:/app/models
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    command: >
      bash -c "
        pip install -r /tmp/requirements.txt &&
        uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      "

  celery:
    build: ./app/docker/fastapi
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/1
      - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - ./app/backend:/app
      - ./app/docker/fastapi/requirements.txt:/tmp/requirements.txt
      - ./storage:/app/storage
      - ./models:/app/models
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    command: >
      bash -c "
        pip install -r /tmp/requirements.txt &&
        celery -A app.workers.celery_app worker --loglevel=info --reload
      "

  frontend:
    build: ./app/docker/quasar
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=${API_BASE_URL}
    volumes:
      - ./app/frontend:/app
    restart: unless-stopped
    command: >
      bash -c "
        npm install &&
        quasar dev --host 0.0.0.0
      "

# Remove the volumes section since we're using local directories